image: maven:3-jdk-8-alpine

variables:
  MAVEN_CLI_OPTS: "-s .ci/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests=false -Dmaven.test.failure.ignore=false test
  allow_failure: true

deploy_snapshot:
  stage: deploy
  environment: snapshot
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
  artifacts:
    paths:
      - target/*.jar

# temp. disabled
#deploy_release:
#  stage: deploy
#  environment: release
#  when: manual
#  script:
#    - mvn $MAVEN_CLI_OPTS release:prepare release:perform
