image: maven:3-jdk-8-alpine

variables:
  MAVEN_CLI_OPTS: "-s .ci/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -U clean compile    # always re-fetch snapshots

test:jdk8:
  stage: test
  image: maven:3-jdk-8-alpine
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests=false -DskipITs=true -Dmaven.test.failure.ignore=false test
  allow_failure: true

test:jdk10:
  stage: test
  image: maven:3-jdk-10
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests=false -DskipITs=true -Dmaven.test.failure.ignore=false test
  allow_failure: true

test:jdk11:
  stage: test
  image: maven:3-jdk-11
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests=false -DskipITs=true -Dmaven.test.failure.ignore=false test
  allow_failure: true

test:jdk12:
  stage: test
  image: maven:3-jdk-12-alpine
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests=false -DskipITs=true -Dmaven.test.failure.ignore=false test
  allow_failure: true

deploy_snapshot:
  stage: deploy
  environment: snapshot
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master@tinyMediaManager/api-scraper
  artifacts:
    paths:
      - target/*.jar

# temp. disabled
#deploy_release:
#  stage: deploy
#  environment: release
#  when: manual
#  script:
#    - mvn $MAVEN_CLI_OPTS release:prepare release:perform
