image: maven:3-jdk-8-alpine

variables:
  MAVEN_CLI_OPTS: "-s .ci/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -U clean compile    # always re-fetch snapshots

test:jdk8:
  stage: test
  image: maven:3-jdk-8-alpine
  only:
    - pushes
  allow_failure: true
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests=false -DskipITs=true -Dmaven.test.failure.ignore=false test

test:jdk10:
  stage: test
  image: maven:3-jdk-10
  only:
    - pushes
  allow_failure: true
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests=false -DskipITs=true -Dmaven.test.failure.ignore=false test

test:jdk11:
  stage: test
  image: maven:3-jdk-11
  only:
    - pushes
  allow_failure: true
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests=false -DskipITs=true -Dmaven.test.failure.ignore=false test

test:jdk12:
  stage: test
  image: maven:3-jdk-12-alpine
  only:
    - pushes
  allow_failure: true
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests=false -DskipITs=true -Dmaven.test.failure.ignore=false test

sonarqube-qa:
  stage: test
  only:
    - pushes
  allow_failure: true
  script:
    - mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.projectKey=org.tinymediamanager:api-scraper -Dsonar.organization=tinymediamanager -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONARCLOUD_API_TOKEN}

deploy_snapshot:
  stage: deploy
  environment:
    name: snapshot
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master@tinyMediaManager/api-scraper
  artifacts:
    paths:
      - target/*.jar

# temp. disabled
#deploy_release:
#  stage: deploy
#  environment: release
#  when: manual
#  script:
#    - mvn $MAVEN_CLI_OPTS release:prepare release:perform
