language: java

script: mvn test -B -DskipTests=false

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk8
    - os: linux:
      dist: trusty
      jdk: oraclejdk9
    - os: osx
      osx_image: xcode9.3
